### PR TITLE
Fix UI & Responsive

### PR DESCRIPTION
**Pull request by alidihaw**
Upwork Profile: https://www.upwork.com/freelancers/alidihaw

### CODE REVIEW

**Comment by lordspace** [comment]
for some reason I can't see the changes

**Comment by lordspace** [comment]
We couldn’t display that commit for review.

Commits that don’t share a common merge base with the base branch are not supported.
You can [view the full commit page here](https://github.com/lordspace/onboarding_html_ui/commit/bf8ff478b39d81fb26e1891dc5a2501b624913a8) instead.

**Comment by alidihaw** [comment]
I see, Let me check first

**Comment by lordspace** [comment]
I cloned the did a directory compare.
It's really nice that you've added border radius to make the buttons look like pills.
Great job!

on step 2 the vertical scroll is a lot. that step doesn't have that much of a content.
on step 3 there's lots of left and right padding. or is it because of the small text?

**Comment by alidihaw** [comment]
Step 1 and 2 have a lot scroll because step 3 content, so need to hide content with js
Need logic only Active content active, let me update for this

about step 3 where part you mean have a lots padding?

**Pull request closed without merging**
