### PR TITLE
Fix UI & Responsive

### PR DESCRIPTION
**Pull request by alidihaw**

### CODE REVIEW

**Comment by alidihaw** [comment]
Should be working now @lordspace

**Comment by lordspace** [comment]
thanks! will check

**Comment by alidihaw** [comment]
Let me know if have some feedback, i will fix asap

**Comment by lordspace** [comment]
on mobile
the bottom navigation section covers a little of the content see step 2 and 3. maybe it's a margin/padding issue
image

it's great that you provided a static link to preview.

**Comment by alidihaw** [comment]
Its fixed, 
You can check again in here: https://onboarding-html-ui.web.app/

**Comment by alidihaw** [comment]
created new pr on:
https://github.com/lordspace/onboarding_html_ui/pull/5

**Pull request closed without merging**
